MODEL: 3            # 1: edge model, 2: inpaint model, 3: edge-inpaint model, 4: joint model            # 0: no non-max-suppression, 1: applies non-max-suppression on the external edges by multiplying by Canny
SEED: 10            # random seed
GPU: [3]            # list of gpu ids
DEBUG: 0            # turns on debugging mode
VERBOSE: 0          # turns on verbose mode in the output console


CHECKPOINTS: /.../checkpoints
LOAD_MODEL: /.../model



TRAIN_CONCAT_FLIST: /.../data/sd1_train.list
VAL_CONCAT_FLIST: /.../data/sd1_val.list


LR: 0.0001                    # learning rate
D2G_LR: 0.1                   # discriminator/generator learning rate ratio
BETA1: 0.5                    # adam optimizer beta1
BETA2: 0.9                    # adam optimizer beta2
BATCH_SIZE: 4                 # input batch size for training
VAL_BATCH_SIZE: 2            # input batch size for validation
RES_NUM: 8                     # res-unit number in generator model
BASE_CHANNEL: 64               # the first channel size in generator model
SAMPLE_NUM: 2                  # down and up sample number in generator model
INPUT_SIZE: 512               # input image size for training 0 for original size
MAX_ITERS: 2e6                # maximum number of iterations to train the model
RATE: 1
EPOCH: 500                     # epoch number to train the model

EDGE_THRESHOLD: 0.5           # edge detection threshold
L1_LOSS_WEIGHT: 1             # l1 loss weight
FM_LOSS_WEIGHT: 10            # feature-matching loss weight
STYLE_LOSS_WEIGHT: 120          # style loss weight
TOTAL_LOSS_WEIGHT: 1           #total variation weight
CONTENT_LOSS_WEIGHT: 0.1        # perceptual loss weight
INPAINT_ADV_LOSS_WEIGHT: 0.01 # adversarial loss weight

GAN_LOSS: nsgan               # nsgan | lsgan | hinge
GAN_POOL_SIZE: 0              # fake images pool size

SAVE_INTERVAL: 1000 #4300          # how many iterations to wait before saving model (0: never)ckp
SUMMARY_INTERVAL: 1000        # how many iterations to wait before summary model (0: never)tensorboard
SAMPLE_INTERVAL: 1000         # how many iterations to wait before sampling (0: never)
SAMPLE_SIZE: 12               # number of images to sample
EVAL_INTERVAL: 0              # how many iterations to wait before model evaluation (0: never)
LOG_INTERVAL: 10              # how many iterations to wait before logging training status (0: never)
